<!--<!DOCTYPE html>
<html lang="en">
<head>
    <title>Cart</title>
</head>
<body>
<div class="container">
    <h3>Cart</h3>
    <div class="card-deck">
        <?php foreach ($products as $product): ?>
        <div class="card">
    <div class="card-footer"><?php echo $product->getPrice(); ?></div>
    <div class="card-footer"><?php echo $product->getQuantity(); ?></div>
    <div class="card-name"><?php echo $product->getName(); ?></div>
    </div>
        <?php endforeach; ?>
    </div>
</div>
</body>
<style>
    .container {
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
        height: 100vh;
    }

    .card-deck {
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
        gap: 1rem;
    }
    body {
        color: blue;
    }

    a {
        text-decoration: none;
    }

    a:hover {
        text-decoration: underline;
    }

    h3 {
        line-height: 3em;
    }

    .card {
        max-width: 16rem;
    }

    .card:hover {
        box-shadow: 1px 2px 10px lightgray;
        transition: 0.2s;
    }

    .card-header {
        font-size: 13px;
        color: red;
        background-color: white;
    }

    .text-muted {
        font-size: 11px;
    }

    .card-footer{
        font-weight: bold;
        font-size: 18px;
        background-color: white;
    }
</style>
