<body>
<div class="container">
    <h1>Корзина</h1>
    <?php foreach ($products as $product): ?>
        <div class="card-details">
            <div class="card-name" style="text-align: center;"><?php echo ($product->getName()); ?></div>
            <div class="card-price" style="text-align: center;"><?php echo $product->getPrice() . " руб"; ?></div>
            <div class="card-wheel" style="text-align: center;">
                <span><?php $quantity = $cartProducts[$product->getId()]->getQuantity(); echo $quantity . " шт"; ?></span>
            </div>
        </div>
        <?php $summa = 0; ?>
        <?php $summa += $product->getPrice()*$quantity; ?>
    <?php endforeach; ?>
    <div class="checkout-total" style="text-align: center;">
        <h6>Итого:</h6>
        <p><?php echo $summa ." руб"; ?></p><a href="/order"><button type="submit" class="btn">Оформить заказ </button></a>
    </div>
</div>
</body>
    <style>
        .container {
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
            height: 100vh;
        }

        .card-deck {
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
            gap: 1rem;
        }

        body {
            color: blue;
        }

        a {
            text-decoration: none;
        }

        a:hover {
            text-decoration: underline;
        }

        h3 {
            line-height: 3em;
        }

        .card {
            max-width: 16rem;
        }

        .card:hover {
            box-shadow: 1px 2px 10px lightgray;
            transition: 0.2s;
        }

        .card-header {
            font-size: 13px;
            color: red;
            background-color: white;
        }

        .text-muted {
            font-size: 11px;
        }

        .card-footer {
            font-weight: bold;
            font-size: 18px;
            background-color: white;
        }
    </style>
