<body>
<header>
    <div class="header-cart">
        <a href="/cart"><button type="submit" class="btn-cart">
                <img class="img-cart" src="https://cdn-icons-png.flaticon.com/512/60/60756.png" alt="">
            </button></a>
    </div>
</header>
<div class="container">
    <h3>Catalog</h3>
    <div class="card-deck">
        <?php foreach ($products as $product): ?>
                <div class="card text-center">
                    <form method="POST" onsubmit="return false" class="addProduct">
                        <div class="card-header">
                            <div class="card-body">
                                <img class="card-img-top" src='https://img.freepik.com/premium-photo/slices-of-fresh-banana-and-pieces-of-strawberries-with-mint-leaves-on-white-background_124507-38152.jpg' alt=''>
                                <p class="card-text text-muted"><?php echo ucfirst($product->getName()); ?> </p>
                                <h5 class="card-title">Фрукты</h5>
                                <div class="card-footer">
                                    <?php echo $product->getPrice() . " pублей"; ?><br>
                                    <label>
                                        <input type="text" placeholder="product_id" name="product_id" hidden="" value="<?php echo $product->getId(); ?>">
                                        <input type="text" placeholder="quantity" name="quantity" class="quantity">
                                    </label>
                                    <button type="submit" class="btn">Add to cart</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
        <?php endforeach; ?>
    </div>
</div>
</body>
<script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
<script>
    $("document").ready(function() {
            $('.addProduct').submit(function() {
                $.ajax({
                    type: "POST",
                    url: "/add-product",
                    data: $(this).serialize(),
                    success: function() {
                        console.log('done');
                        $('input.quantity').val('');
                    }
                })
            });
        });
</script>
<style>
    body {
        font-family: sans-serif;
    }

    a {
        text-decoration: none;
    }

    a:hover {
        text-decoration: none;
    }

    h3 {
        line-height: 3em;
    }

    .card {
        max-width: 16rem;
    }

    .card:hover {
        box-shadow: 1px 2px 10px lightgray;
        transition: 0.2s;
    }

    .card-header {
        font-size: 13px;
        color: gray;
        background-color: white;
    }

    .text-muted {
        font-size: 11px;
    }

    .card-footer {
        font-weight: bold;
        font-size: 18px;
        background-color: white;
    }

    .card-img-top {
        display: block;
        margin-left: auto;
        margin-right: auto;
    }
</style>
<!--                    <form method="POST" onsubmit="return false" class="addProduct"
                    <div class="card-header">
                        Фрукты
                        <img class="card-img-top" src='https://img.freepik.com/premium-photo/slices-of-fresh-banana-and-pieces-of-strawberries-with-mint-leaves-on-white-background_124507-38152.jpg' alt=''>
                    </div>
                    <div class="card-body">
                        <p class="card-text"><?php /*echo $product->getName(); */?> </p>
                        <div class="text"><?php /*echo $product->getDescription();*/?></div>
                        <label>
                            <input type="text" placeholder="product_id" name="product_id" value="<?php /*echo $product->getId();*/?>">
                        </label>
                        <?php /*if (isset($errors['product_id'])): */?>
                            <label style="color: red"><?php /*echo $errors['product_id'];*/?></label>
                        <?php /*endif; */?>
                        <label>
                            <input type="text" placeholder="quantity" name="quantity" required>
                        </label>
                        <?php /*if (isset($errors['quantity'])): */?>
                            <label style="color: red"><?php /*echo $errors['quantity'];*/?></label>
                        <?php /*endif; */?>
                        <div class="card-footer">
                            <?php /*echo $product->getPrice() . " rub"; */?>
                        </div>
                        <button type="submit" class="btn">Add to cart</button>
                    </div>
                    </form>-->