<body>
<header>
    <div class="header-cart">
        <a href="/cart"><button type="submit" class="btn-cart">
                <img class="img-cart" src="https://cdn-icons-png.flaticon.com/512/60/60756.png">
            </button></a>
    </div>
</header>
<div class="container">
    <h3>Catalog</h3>
    <div class="card-deck">
        <?php foreach ($products as $product): ?>
            <form action="/main" method="POST">
                <div class="card text-center">
                    <div class="card-header">
                        Фрукты
                        <img class="card-img-top" src='https://img.freepik.com/premium-photo/slices-of-fresh-banana-and-pieces-of-strawberries-with-mint-leaves-on-white-background_124507-38152.jpg' alt=''>
                    </div>
                    <div class="card-body">
                        <p class="card-text"><?php echo $product->getName(); ?> </p>
                        <div class="text"><?php echo $product->getDescription();?></div>
                        <label>
                            <input type="hidden" placeholder="product-id" name="product-id" value="<?php echo $product->getId();?>">
                        </label>
                        <label>
                            <input type="text" placeholder="quantity" name="quantity" required>
                        </label>
                        <div class="card-footer">
                            <?php echo $product->getPrice() . " rub"; ?>
                        </div>
                        <button type="submit" class="btn">Add to cart</button>
                    </div>
                </div>
            </form>
        <?php endforeach; ?>
    </div>
</div>
</body>

<style>
    body {
        font-family: sans-serif;
    }

    a {
        text-decoration: none;
    }

    a:hover {
        text-decoration: none;
    }

    h3 {
        line-height: 3em;
    }

    .card {
        max-width: 16rem;
    }

    .card:hover {
        box-shadow: 1px 2px 10px lightgray;
        transition: 0.2s;
    }

    .card-header {
        font-size: 13px;
        color: gray;
        background-color: white;
    }

    .text-muted {
        font-size: 11px;
    }

    .card-footer {
        font-weight: bold;
        font-size: 18px;
        background-color: white;
    }

    .card-img-top {
        display: block;
        margin-left: auto;
        margin-right: auto;
    }
</style>
<!--<body>
<header>
    <div class="header-cart">
        <a href="/cart"><button type="submit" class="btn-cart">
                <img class="img-cart" src="https://cdn-icons-png.flaticon.com/512/60/60756.png">
            </button></a>
    </div>
</header>
<div class="container">
    <h3>Catalog</h3>
    <div class="card-deck">
         <?php /*foreach ($products as $product): */?>
            <form action="/main" method="POST">
                <div class="card text-center">
                    <div class="card-header">
                        Фрукты
                        <img class="card-img-top" src='https://img.freepik.com/premium-photo/slices-of-fresh-banana-and-pieces-of-strawberries-with-mint-leaves-on-white-background_124507-38152.jpg' alt=''>
                    </div>
                    <div class="card-body">
                        <p class="card-text"><?php /*echo $product->getName() ; */?> </p>
                        <div class="text"><?php /*echo $product->getDescription();*/?></div>
                        <label>
                            <input type="text" placeholder="product-id" name="product-id" required hidden="" value="<?php /*echo $product->getId();*/?>">
                        </label>
                        <label>
                            <input type="text" placeholder="quantity" name="quantity" required>
                        </label>
                        <div class="card-footer">
                            <?php /*echo $product->getPrice() . " rub"; */?>
                        </div>
                        <a href=""><button type="submit" class="btn">Add to cart</button>
                    </div>
                </div>
            </form>
        <?php /*endforeach; */?>
    </div>
</div>
</body>

<style>
    body {
        font-style: sans-serif;
    }

    a {
        text-decoration: none;
    }

    a:hover {
        text-decoration: none;
    }

    h3 {
        line-height: 3em;
    }

    .card {
        max-width: 16rem;
    }

    .card:hover {
        box-shadow: 1px 2px 10px lightgray;
        transition: 0.2s;
    }

    .card-header {
        font-size: 13px;
        color: gray;
        background-color: white;
    }

    .text-muted {
        font-size: 11px;
    }

    .card-footer {
        font-weight: bold;
        font-size: 18px;
        background-color: white;
    }

    .card-img-top {
        display: block;
        margin-left: auto;
        margin-right: auto;
    }
</style>
-->
