<body>
<div class="container">
    <h3>Catalog</h3>
    <div class="card-deck">
        <?php foreach ($products as $product): ?>
            <form action="/add-product" method="POST">
                <div class="card text-center">
                    <div class="card-header">
                        Фрукты
                        <img class="card-img-top" src='https://img.freepik.com/premium-photo/slices-of-fresh-banana-and-pieces-of-strawberries-with-mint-leaves-on-white-background_124507-38152.jpg' alt=''>
                    </div>
                    <div class="card-body">
                        <p class="card-text"><?php echo $product->getName; ?> </p>
                        <div class="text"><?php echo $product->getDescription;?></div>
                        <label>
                            <input type="text" placeholder="product-id" name="product-id" required hidden="" value="<?php echo $product['id'];?>">
                        </label>
                        <label>
                            <input type="text" placeholder="quantity" name="quantity" required>
                        </label>
                        <div class="card-footer">
                            <?php echo $product->getPrice . " rub"; ?>
                        </div>
                        <button class="btn">add to cart</button>
                    </div>
                </div>
            </form>
        <?php endforeach; ?>
    </div>
</div>
</body>

<style>
    .container {
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
        height: 100vh;
    }

    .card-deck {
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
        gap: 1rem;
    }
    body {
        color: blue;
    }

    a {
        text-decoration: none;
    }

    a:hover {
        text-decoration: underline;
    }

    h3 {
        line-height: 3em;
    }

    .card {
        max-width: 16rem;
    }

    .card:hover {
        box-shadow: 1px 2px 10px lightgray;
        transition: 0.2s;
    }

    .card-header {
        font-size: 13px;
        color: red;
        background-color: white;
    }

    .card-footer{
        font-weight: bold;
        font-size: 18px;
        background-color: white;
    }
</style>